In [1]:
print("Hello World")

Hello World


In [1]:
print("Hello")


Hello


In [3]:
print("Welcome to machine learning python")

Welcome to machine learning python


In [3]:
import numpy as np

In [4]:
[1,2,3,4]

[1, 2, 3, 4]

In [5]:
a=np.array([1,2,3,4])    #print array with library numpy
print(a)

[1 2 3 4]


In [6]:
print("array a:",a)
print(f"array:{a}")
print("array a:{}".format(a))

array a: [1 2 3 4]
array:[1 2 3 4]
array a:[1 2 3 4]


In [7]:
print(f"ndin:{a.ndim}")
print(f"size:{a.size}") # show size
print(f"shape:{a.shape}") # shape
print(f"dtype:{a.dtype}") #datatypes
print(f"itemsize:{a.itemsize}")#how many items in array

ndin:1
size:4
shape:(4,)
dtype:int64
itemsize:8


In [8]:
b=np.array([[1,2,3],[4,5,6]]) 
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
b=np.array([4,5,6,7])
c=np.add(a,b) #addition of array
print(c)

[ 5  7  9 11]


In [10]:
b=np.array([4,5,6,7])
d=np.subtract(a,b) #substract
print(d)

[-3 -3 -3 -3]


In [11]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.add(a,b) 
print(d)

[[ 2  4  6  8]
 [ 5  7  9 11]]


In [12]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.subtract(a,b)
print(d)

[[ 0  0  0  0]
 [-3 -3 -3 -3]]


In [13]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.divide(a,b) #division
print(d)

[[1.         1.         1.         1.        ]
 [0.25       0.4        0.5        0.57142857]]


In [14]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.multiply(a,b) #multiplication
print(d)

[[ 1  4  9 16]
 [ 4 10 18 28]]


In [15]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.mod(a,b) #module or reminder
print(d)

[[0 0 0 0]
 [1 2 3 4]]


In [16]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.power(a,b) #power 
print(d)

[[    1     4    27   256]
 [    1    32   729 16384]]


In [17]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.abs(a,b) #absolute value
print(d)

[[1 2 3 4]
 [1 2 3 4]]


In [18]:
b=np.array([[1,2,3,4],[4,5,6,7]])
d=np.remainder(a,b)
print(d)

[[0 0 0 0]
 [1 2 3 4]]


In [19]:
s=np.array(["utsav","vishv","digu","bhavdip"])
print(s)
print(f"size:{a.size}")
print(f"shape:{a.shape}")
print(f"dtype:{a.dtype}")
print(f"itemsize:{a.itemsize}")

['utsav' 'vishv' 'digu' 'bhavdip']
size:4
shape:(4,)
dtype:int64
itemsize:8


In [64]:
z=np.zeros((2,3)) #used to create an array with zeros
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [65]:
one=np.ones((3,3))  #used to create a new array of given shape and type filled with ones
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [67]:
empty=np.empty((2,2)) #used to return new array of given shape and type
print(empty)

[[6.9063836e-310 6.9063836e-310]
 [6.9063836e-310 6.9063836e-310]]


In [74]:
ar=np.arange(1,5,0.5) #return an array with evenly spaced elements as per the interval                   
print(ar)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [81]:
l=np.linspace(1,5,8) #space between the specified interval
print(l)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [83]:
r=np.random.random((2,3)) #returns a random float number between 0 and 1
print(r)

[[0.59659405 0.55048859 0.46857933]
 [0.40515285 0.9876724  0.466082  ]]
